Betasuchus/Areas/ServiceManagement/Models/OfferHistory/ActivateOfferViewModel.cs
using Betasuchus.Admin.Infrastructure;
using Betasuchus.Application.Commands.OfferManagement;
using Betasuchus.Application.Infrastructure;
using System;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class ActivateOfferViewModel : IViewModel
    {
        public int Id { get; set; }

        public DateTime? ExpireDate { get; set; }

        public Command ToCommand()
        {
            var command = new ActivateExpiredOfferCommand
            {
                Id = Id,
                ExpireDate = ExpireDate.Value
            };

            return command;
        }
    }
}

Betasuchus/Areas/ServiceManagement/Models/OfferHistory/OfferHistoryFilterViewModel.cs
using Betasuchus.Admin.Infrastructure;
using Betasuchus.Admin.Models.Shared.KtCommon;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.OfferHistory
{
    public class OfferHistoryFilterViewModel : SortedAndPagedListRequestBase
    {
    }
}

Betasuchus/Areas/ServiceManagement/Controllers/OfferHistoryController.cs
using Betasuchus.Admin.Areas.ServiceManagement.Models.OfferHistory;
using Betasuchus.Admin.Areas.ServiceManagement.Models.Offers;
using Betasuchus.Admin.Infrastructure;
using Betasuchus.Admin.Models.Shared.KtCommon;
using Betasuchus.Admin.Resources;
using Betasuchus.Application.Commands.OfferManagement;
using Betasuchus.Application.Infrastructure;
using Betasuchus.Application.Queries.Offers;
using Betasuchus.Infrastructure.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Threading.Tasks;
using Wandio.Web.Mvc;

namespace Betasuchus.Admin.Areas.ServiceManagement.Controllers
{
    [Area(AreaConstants.AreaName)]
    [Authorize(Roles = "editor,admin")]
    public class OfferHistoryController : Controller
    {
        private readonly CommandExecutor _commandExecutor;
        private readonly QueryExecutor _queryExecutor;
        private readonly IStringLocalizer<Translations> _localizer;

        public OfferHistoryController(
            CommandExecutor commandExecutor,
            QueryExecutor queryExecutor,
            IStringLocalizer<Translations> localizer)
        {
            _commandExecutor = commandExecutor;
            _queryExecutor = queryExecutor;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var model = new OfferHistoryFilterViewModel
            {
                KtCardModel = new KtCardModel
                {
                    KtCardActionModel = new KtCardActionModel()
                    {
                        ActionItems = null
                    },
                    KtCardInfoModel = new KtCardInfoModel
                    {
                        Title = _localizer["OffersHistory"]
                    },
                    KtDatatableModel = new KtDatatableModel
                    {
                        DatatableName = "Offers",
                        ReadUrl = Url.Action(nameof(Offers), nameof(OfferHistoryController).TrimController(), new { Area = AreaConstants.AreaName }),
                        ColumnFunctionName = "initOffersData",
                        DeleteAction = new KtActionModel
                        {
                            ActionUrl = Url.Action(nameof(Delete), nameof(OfferHistoryController).TrimController(), new { Area = AreaConstants.AreaName }),
                            IconClassName = "fa fa-ban",
                            Name = "Delete"
                        },
                        AdditionalActions = new List<KtActionModel>()
                        .AddIf(User.IsInRole("admin"),
                            new KtActionModel
                            {
                                ActionUrl = Url.Action(nameof(Activate), nameof(OfferHistoryController).TrimController(), new { Area = AreaConstants.AreaName }),
                                Name = "Activate",
                                IconClassName = "fa fa-check",
                                Hide = false,
                            })
                    }
                }
            };

            return View(model);
        }

        public async Task<IActionResult> Offers(OfferFilterViewModel query)
        {
            var offerQuery = new OffersQuery()
            {
                Page = query.Page,
                PageSize = query.PageSize,
                SortBy = query.SortBy ?? "Id",
                SortOrder = query.SortOrder,
                Active = false
            };

            var result = await _queryExecutor.ExecutePagedQueryAsync<OffersQuery, OffersQueryResult>(offerQuery);

            query.Total = result.Data.TotalCount;

            return query.ToDataSourceResult(result.Data.Offers);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Activate(int id)
        {
            return await Task.FromResult(View(new ActivateOfferViewModel() { Id = id }));
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Activate(ActivateOfferViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());
            if (response.Success)
            {
                this.SetSuccessMessage("Offer add success");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer add error");
            return this.JsonFail();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(DeleteOfferCommand command)
        {
            var response = await _commandExecutor.ExecuteAsync(command);

            if (response.Success)
            {
                this.SetSuccessMessage("Offer deleted");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer delete error");
            return this.JsonFail();
        }
    }
}

Betasuchus/Areas/ServiceManagement/Views/OfferHistory/Activate.cshtml
@model ActivateOfferViewModel

@{
    Layout = null;
}

<div class="modal" id="js-entity-action-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Activate Offer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="OfferHistory" asp-action="Activate" method="post" class="form">
                    <input type="hidden" asp-for="Id" />
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-1 col-md-1"></div>
                            <div class="col-xl-10 col-md-10">

                                <div class="form-group">
                                    <label asp-for="ExpireDate"></label>
                                    @Html.EditorFor(m => m.ExpireDate)
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="ExpireDate" class="fv-help-block"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-1 col-md-1"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary js-entity-action">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 

Betasuchus/Areas/ServiceManagement/Views/OfferHistory/index.cshtml
@model OfferHistoryFilterViewModel

<div class="kt-search-form">
    <div class="kt-search-body row align-items-center">
        <div class="col-lg-10 col-xl-12">
            <div class="d-flex justify-content-between flex-wrap align-items-center">
                <div class="col-md-4 my-2 my-md-0">
                </div>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("_KtCard", Model.KtCardModel)