Betasuchus/Areas/ServiceManagement/Models/Offers/BoomViewModel.cs
using Betasuchus.Application.Commands.OfferManagement.Boom;
using Betasuchus.Application.Infrastructure;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class BoomViewModel : ExtendedOfferViewModel
    {
        public override Command ToCommand()
        {
            var command = new CreateBoomCommand()
            {
                Amount = Amount,
                ExpireDate = ExpireDate.Value,
                CategoryId = CategoryId,
                Expire = Expire,
                FreebetNominal = FreebetNominal,
                GameType = GameType,
                DiscountedPrice = DiscountedPrice,
                OfferText = OfferText,
                Price = Price,
                Thumbnail = Thumbnail,
                GameName = GameName
            };

            return command;
        }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/EgtViewModel.cs
using Betasuchus.Application.Commands.OfferManagement.EGT;
using Betasuchus.Application.Infrastructure;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class EgtViewModel : SlotOfferViewModel
    {
        public override Command ToCommand()
        {
            var command = new CreateEGTCommand
            {
                Amount = Amount,
                CampaignId = CampaignId,
                CategoryId = CategoryId,
                Expire = Expire,
                ExpireDate = ExpireDate.Value,
                FreebetNominal = FreebetNominal,
                GameName = GameName,
                GameType = GameType,
                DiscountedPrice = DiscountedPrice,
                OfferText = OfferText,
                Price = Price,
                ProviderId = ProviderId,
                Thumbnail = Thumbnail
            };

            return command;
        }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/OfferFilterViewModel.cs
using Betasuchus.Admin.Models.Shared.KtCommon;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class OfferFilterViewModel : SortedAndPagedListRequestBase
    {
        public string Name { get; set; }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/OfferViewModels/ExtendedOfferViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public abstract class ExtendedOfferViewModel : OfferViewModel
    {
        public int Expire { get; set; }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/OfferViewModels/OfferViewModel.cs
using Betasuchus.Admin.Infrastructure;
using Betasuchus.Application.Infrastructure;
using Betasuchus.Domain.OfferManagement;
using Betasuchus.Shared;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public abstract class OfferViewModel : IViewModel
    {
        public int Amount { get; set; }

        public DateTime? ExpireDate { get; set; }

        public decimal Price { get; set; }

        public decimal DiscountedPrice { get; set; }

        public long CategoryId { get; set; }

        public IFormFile Thumbnail { get; set; }

        public MultilanguageString OfferText { get; set; }

        public int FreebetNominal { get; set; }

        public string CampaignId { get; set; }

        public GameType GameType { get; set; }

        public IEnumerable<SelectListItem> GameTypes { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }

        public MultilanguageString GameName { get; set; }

        public abstract Command ToCommand();
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/OfferViewModels/SlotOfferViewModel.cs
using Betasuchus.Shared;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public abstract class SlotOfferViewModel : ExtendedOfferViewModel
    {
        public long ProviderId { get; set; }

        public IEnumerable<SelectListItem> Providers { get; set; }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/PlayNGoViewModel.cs
using Betasuchus.Application.Commands.OfferManagement.PlayNGo;
using Betasuchus.Application.Infrastructure;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class PlayNGoViewModel : SlotOfferViewModel
    {
        public string TriggerId { get; set; }

        public override Command ToCommand()
        {
            var command = new CreatePlayNGoCommand
            {
                Thumbnail = Thumbnail,
                ProviderId = ProviderId,
                Price = Price,
                Amount = Amount,
                CategoryId = CategoryId,
                Expire = Expire,
                ExpireDate = ExpireDate.Value,
                FreebetNominal = FreebetNominal,
                GameName = GameName,
                GameType = GameType,
                DiscountedPrice = DiscountedPrice,
                OfferText = OfferText,
                TriggerId = TriggerId
            };

            return command;
        }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/PokerViewModel.cs
using Betasuchus.Application.Commands.OfferManagement.Poker;
using Betasuchus.Application.Infrastructure;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class PokerViewModel : ExtendedOfferViewModel
    {
        public string BonusCode { get; set; }

        public override Command ToCommand()
        {
            var command = new CreatePokerCommand()
            {
                Price = Price,
                OfferText = OfferText,
                Amount = Amount,
                BonusCode = BonusCode,
                CategoryId = CategoryId,
                Expire = Expire,
                ExpireDate = ExpireDate.Value,
                FreebetNominal = FreebetNominal,
                GameType = GameType,
                DiscountedPrice = DiscountedPrice,
                Thumbnail = Thumbnail,
                GameName = GameName
            };

            return command;
        }
    }
}

Betasuchus/Areas/ServiceManagement/Models/Offers/SportViewModel.cs
using Betasuchus.Application.Commands.OfferManagement.Sport;
using Betasuchus.Application.Infrastructure;

namespace Betasuchus.Admin.Areas.ServiceManagement.Models.Offers
{
    public class SportViewModel : ExtendedOfferViewModel
    {
        public override Command ToCommand()
        {
            var command = new CreateSportCommand()
            {
                Amount = Amount,
                OfferText = OfferText,
                CategoryId = CategoryId,
                ExpireDate = ExpireDate.Value,
                FreebetNominal = FreebetNominal,
                GameType = GameType,
                DiscountedPrice = DiscountedPrice,
                Price = Price,
                Thumbnail = Thumbnail,
                Expire = Expire,
                GameName = GameName
            };

            return command;
        }
    }
}

Betasuchus/Areas/ServiceManagement/Controllers/OfferController.cs
using Betasuchus.Admin.Areas.ServiceManagement.Models.Offers;
using Betasuchus.Admin.Infrastructure;
using Betasuchus.Admin.Models.Shared.KtCommon;
using Betasuchus.Admin.Resources;
using Betasuchus.Application.Commands.OfferManagement;
using Betasuchus.Application.Infrastructure;
using Betasuchus.Application.Queries.Categories;
using Betasuchus.Application.Queries.Offers;
using Betasuchus.Application.Queries.Providers;
using Betasuchus.Domain.OfferManagement;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wandio.Web.Mvc;

namespace Betasuchus.Admin.Areas.ServiceManagement.Controllers
{
    [Area(AreaConstants.AreaName)]
    [Authorize(Roles = "editor,admin")]
    public class OfferController : Controller
    {
        private readonly CommandExecutor _commandExecutor;
        private readonly QueryExecutor _queryExecutor;
        private readonly IStringLocalizer<Translations> _localizer;

        public OfferController(
            CommandExecutor commandExecutor,
            QueryExecutor queryExecutor,
            IStringLocalizer<Translations> localizer)
        {
            _commandExecutor = commandExecutor;
            _queryExecutor = queryExecutor;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var model = new OfferFilterViewModel
            {
                KtCardModel = new KtCardModel
                {
                    KtCardActionModel = new KtCardActionModel()
                    {
                        ActionItems = new List<KtActionModel>()
                        {
                            new KtActionModel
                            {
                                Name = "Add",
                                SubActions = new List<KtActionModel>(){
                                    new KtActionModel{
                                        ActionUrl = Url.Action(nameof(AddEgt), nameof(OfferController).TrimController(), new{Area=AreaConstants.AreaName }),
                                        Name = nameof(AddEgt),
                                        CustomClassName = "btn-primary",
                                        IconClassName = "fa fa-plus"
                                    },
                                    new KtActionModel{
                                        ActionUrl = Url.Action(nameof(AddPlayNGo), nameof(OfferController).TrimController(), new{Area=AreaConstants.AreaName }),
                                        Name = nameof(AddPlayNGo),
                                        CustomClassName = "btn-primary",
                                        IconClassName = "fa fa-plus"
                                    },
                                    new KtActionModel{
                                        ActionUrl = Url.Action(nameof(AddPoker), nameof(OfferController).TrimController(), new{Area=AreaConstants.AreaName }),
                                        Name = nameof(AddPoker),
                                        CustomClassName = "btn-primary",
                                        IconClassName = "fa fa-plus"
                                    },
                                    new KtActionModel{
                                        ActionUrl = Url.Action(nameof(AddTableGames), nameof(OfferController).TrimController(), new{Area=AreaConstants.AreaName }),
                                        Name = nameof(AddTableGames),
                                        CustomClassName = "btn-primary",
                                        IconClassName = "fa fa-plus"
                                    },
                                    new KtActionModel{
                                        ActionUrl = Url.Action(nameof(AddSport), nameof(OfferController).TrimController(), new{Area=AreaConstants.AreaName }),
                                        Name = nameof(AddSport),
                                        CustomClassName = "btn-primary",
                                        IconClassName = "fa fa-plus"
                                    },
                                    new KtActionModel{
                                        ActionUrl = Url.Action(nameof(AddBoom), nameof(OfferController).TrimController(), new{Area=AreaConstants.AreaName }),
                                        Name = nameof(AddBoom),
                                        CustomClassName = "btn-primary",
                                        IconClassName = "fa fa-plus",
                                    },
                                }
                            }
                        }
                    },
                    KtCardInfoModel = new KtCardInfoModel
                    {
                        Title = _localizer["Offers"]
                    },
                    KtDatatableModel = new KtDatatableModel
                    {
                        DatatableName = "Offers",
                        ReadUrl = Url.Action(nameof(Offers), nameof(OfferController).TrimController(), new { Area = AreaConstants.AreaName }),
                        ColumnFunctionName = "initOffersData",
                        DeleteAction = new KtActionModel
                        {
                            ActionUrl = Url.Action(nameof(Delete), nameof(OfferController).TrimController(), new { Area = AreaConstants.AreaName }),
                            IconClassName = "fa fa-ban",
                            Name = "Delete"
                        }
                    }
                }
            };

            return View(model);
        }

        public async Task<IActionResult> Offers(OfferFilterViewModel query)
        {
            var offerQuery = new OffersQuery()
            {
                Page = query.Page,
                PageSize = query.PageSize,
                SortBy = query.SortBy ?? "Id",
                SortOrder = query.SortOrder,
                Active = true
            };

            var result = await _queryExecutor.ExecutePagedQueryAsync<OffersQuery, OffersQueryResult>(offerQuery);

            query.Total = result.Data.TotalCount;

            return query.ToDataSourceResult(result.Data.Offers);
        }

        public async Task<IActionResult> AddEgt()
        {
            var model = new EgtViewModel();
            await SetSelectLists(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEgt(EgtViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());
            if (response.Success)
            {
                this.SetSuccessMessage("Offer add success");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer add error");
            return this.JsonFail();
        }

        public async Task<IActionResult> AddPlayNGo()
        {
            var model = new PlayNGoViewModel();
            await SetSelectLists(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddPlayNGo(PlayNGoViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());
            if (response.Success)
            {
                this.SetSuccessMessage("Offer add success");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer add error");
            return this.JsonFail();
        }

        public async Task<IActionResult> AddBoom()
        {
            var model = new BoomViewModel();
            await SetSelectLists(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddBoom(BoomViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());
            if (response.Success)
            {
                this.SetSuccessMessage("Offer add success");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer add error");
            return this.JsonFail();
        }

        public async Task<IActionResult> AddSport()
        {
            var model = new SportViewModel();
            await SetSelectLists(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddSport(SportViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());
            if (response.Success)
            {
                this.SetSuccessMessage("Offer add success");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer add error");
            return this.JsonFail();
        }

        public async Task<IActionResult> AddTableGames()
        {
            var model = new TableGameViewModel();
            await SetSelectLists(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddTableGames(TableGameViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());
            if (response.Success)
            {
                this.SetSuccessMessage("Offer add success");
                return this.JsonSuccess();
            }

            this.SetErrorMessage("Offer add error");
            return this.JsonFail();
        }

        public async Task<IActionResult> AddPoker()
        {
            var model = new PokerViewModel();
            await SetSelectLists(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddPoker(PokerViewModel command)
        {
            var response = await _commandExecutor.ExecuteAsync(command.ToCommand());

Betasuchus/Areas/ServiceManagement/Views/Offer/Activate.cshtml
@model ActivateOfferViewModel

@{
    Layout = null;
}

<div class="modal" id="js-entity-action-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Activate Offer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Offer" asp-action="Activate" method="post" class="form">
                    <input type="hidden" asp-for="Id" />
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-1 col-md-1"></div>
                            <div class="col-xl-10 col-md-10">

                                <div class="form-group">
                                    <label asp-for="ExpireDate"></label>
                                    @Html.EditorFor(m => m.ExpireDate)
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="ExpireDate" class="fv-help-block"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-1 col-md-1"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary js-entity-action">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 

Betasuchus/Areas/ServiceManagement/Views/Offer/AddBoom.cshtml
@model BoomViewModel

@{
    Layout = null;
}

<div class="modal" id="js-entity-action-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Boom Offer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Offer" asp-action="AddBoom" method="post" class="form" enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-1 col-md-1"></div>
                            <div class="col-xl-10 col-md-10">

                                <div class="form-group">
                                    <label asp-for="CategoryId"></label>
                                    <select asp-for="CategoryId" asp-items="Model.Categories" data-placeholder="Provider" class="js-select2-search w-100 form-control form-control-solid"></select>
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="CategoryId" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="GameType"></label>
                                    <select asp-for="GameType" asp-items="Model.GameTypes" data-placeholder="GameType" class="js-select2-search w-100 form-control form-control-solid"></select>
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="GameType" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="CampaignId"></label>
                                    <input asp-for="CampaignId" data-placeholder="CampaignId" class="w-100 form-control form-control-solid" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="CampaignId" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Amount"></label>
                                    <input asp-for="Amount" data-placeholder="Amount" class="w-100 form-control form-control-solid" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="Amount" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="ExpireDate"></label>
                                    @Html.EditorFor(m => m.ExpireDate)
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="ExpireDate" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Price"></label>
                                    <input asp-for="Price" data-placeholder="Price" class="w-100 form-control form-control-solid" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="Price" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="DiscountedPrice"></label>
                                    <input asp-for="DiscountedPrice" data-placeholder="DiscountedPrice" class="w-100 form-control form-control-solid" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="DiscountedPrice" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="FreebetNominal"></label>
                                    <input asp-for="FreebetNominal" data-placeholder="FreebetNominal" class="w-100 form-control form-control-solid" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="FreebetNominal" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Thumbnail"></label>
                                    <input asp-for="Thumbnail" data-placeholder="Thumbnail" class="w-100 form-control form-control-solid" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="Thumbnail" class="fv-help-block"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Expire"></label>
                                    <input asp-for="Expire" data-placeholder="Expire" class="w-100 form-control form-control-solid date" />
                                    <div class="fv-plugins-message-container">
                                        <span asp-validation-for="Expire" class="fv-help-block"></span>
                                    </div>
                                </div>

                                @Html.EditorFor(m => m.GameName, new { TranslationTitle = "Game name" })

                                @Html.EditorFor(m => m.OfferText, new { TranslationTitle = "Offer text" })

                            </div>
                            <div class="col-xl-1 col-md-1"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary js-entity-action">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Betasuchus/Areas/ServiceManagement/Views/Offer/index.cshtml
@model OfferFilterViewModel

<div class="kt-search-form">
    <div class="kt-search-body row align-items-center">
        <div class="col-lg-10 col-xl-12">
            <div class="d-flex justify-content-between flex-wrap align-items-center">
                <div class="col-md-4 my-2 my-md-0">
                </div>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("_KtCard", Model.KtCardModel)